### ISSUE TITLE
IR3 compatibility

### ISSUE THREAD

**Issue by Deadlock989** [tburrows13/SpidertronPatrols#3]
Factorio 1.1.94, IR 3.1.9, SP 2.4.9

I've been messing around with a new vehicle based on the spidertron prototype recently and tried out your excellent Patrols and Enhancements mods for the first time. Unfortunately Patrols fails to load as it's depending on an item which was removed in IR 3.1.0, `gold-radio`. The radio components were discontinued in favour of regular electronics - the nearest equivalent to that tier of radio would be an advanced circuit. Cheers.

**Comment by tburrows13** [comment]
Thanks - I have had a couple of reports about this already, and I have now finally got around to fixing it. Glad to see that the mod is useful to you!

I wonder if your 'spidertron' vehicle will require fuel? Currently the only options for automated fueling of spidertrons is logistics requests or https://mods.factorio.com/mod/exotic-industries-fueler. I started work a while ago on functionality for this mod's dock where you can set it to connect to the spidertron's fuel inventory rather than its main one, primarily for K2 and Lex's Aircraft mods.

**Comment by Deadlock989** [comment]
Thanks for that.

IR3's personal fuel manager handles spider vehicle fuel slots, but only if a player is riding one. 

Aside from that I have other plans for the mod (it's an add-on for IR3, not part of the main mod), they are still being fleshed out and may not come to fruition. I will check in again with Patrols when plans are firmer.
